### ISSUE TITLE
Doppeltes Schild Icon?

### ISSUE THREAD

**Issue by Swatke** [Fastor01/mc-modgen.com-issuetracker#3]
![Desktop Screenshot 2022 04 15 - 12 47 14 29](https://user-images.githubusercontent.com/61162347/163856510-601bdfc1-e200-4e98-b700-16296e1492f5.png)

**Comment by Intervention128** [comment]
Das  eine ist das Schild zum Abwehren von Attacken, das andere platziert man in der Welt und schreibt sachen drauf. Ist jetzt entsprechend markiert in der deutschen Übersetzung.
